name: Snyk

on:
  push:
    branches: [ master ]

jobs:
  security:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image-name:
          - snowplow/rdb-loader-redshift
          - snowplow/rdb-loader-snowflake
          - snowplow/rdb-loader-databricks
          - snowplow/transformer-kinesis
          - snowplow/transformer-pubsub

    steps:
    - uses: actions/checkout@v3

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/scala@master
      with:
        command: "container monitor ${{ matrix.image-name }}:latest-distroless --app-vulns"
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
