name: Snyk

on:
  push:
    tags:
      - '*'
    branches: [ master ]

jobs:
  security:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app:
          - { project: redshiftLoader, image: snowplow/rdb-loader-redshift }
    #          - snowflakeLoader
    #          - databricksLoader
    #          - transformerKinesis
    #          - transformerPubsub

    steps:
    - uses: actions/checkout@v3

    - name: Get current version
      id: ver
      run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

    - name: Build local distroless image
      run: sbt "project ${{ matrix.app.project }}Distroless" docker:publishLocal

    - name: Docker image ls
      run: docker image ls

    - name: Run Snyk to check for vulnerabilities for an image already published
      uses: snyk/actions/scala@master
      with:
        command: "container monitor snowplow/rdb-loader-redshift:latest-distroless --app-vulns"
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk to check for vulnerabilities hardcoded
      uses: snyk/actions/scala@master
      with:
        command: "container test ${{ matrix.app.image }}:5.3.2-rc2-distroless --app-vulns"
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Print image name and tag
      run: echo "${{ matrix.app.image }}:${{ steps.ver.outputs.tag }}-distroless"

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/scala@master
      with:
        command: "container test ${{ matrix.app }}:${{ steps.ver.outputs.tag }}-distroless --app-vulns"
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}