name: Snyk

on:
  push:
    tags:
      - '*'

jobs:
  security:
    if: ${{ contains(github.ref_name, 'rc') }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        app:
          - { project: redshiftLoader, image: snowplow/rdb-loader-redshift }
    steps:
    - uses: actions/checkout@v3

    - name: Build local distroless image
      run: sbt "project ${{ matrix.app.project }}Distroless" docker:publishLocal

    - name: Docker image ls
      run: docker image ls

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/docker@master
      with:
        image: "${{ matrix.app.image }}:${{ github.ref_name }}-distroless"
        args: "--app-vulns"
        command: monitor
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}